project_name: clockify2cats

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/marvincaspar/clockify2cats/cmd.Version={{ .Env.VERSION }}

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - "!*.md"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: clockify2cats
    directory: Casks
    homepage: "https://github.com/marvincaspar/clockify2cats"

    # Repository to push the generated files to.
    repository:
      owner: marvincaspar
      name: homebrew-tap
      branch: main

    # Git author used to commit to the repository
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # App description
    description: "CLI for exporting clockify data and generate a SAP CATS report as csv"

    # Remove quarantine bit for unsigned binary on macOS
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clockify2cats"]
          end
    generate_completions_from_executable:
      shell_parameter_format: cobra