name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create tag
        id: create_tag
        run: |
          VERSION=$(cat version.txt)

          if [ $(git tag --list "${VERSION}") ]; then
              echo "Tag ${VERSION} already exists."
              echo "is_new_tag=0" >> $GITHUB_OUTPUT
              exit 0
          fi

          git config --global user.name 'GitHub Action'
          git config --global user.email 'github@caspar.dev'
          git tag --annotate "${VERSION}" --message='Created by GitHub Action'
          git push --tags
          echo "is_new_tag=1" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up Go
        if: ${{ steps.create_tag.outputs.is_new_tag == 1 }}
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        if: ${{ steps.create_tag.outputs.is_new_tag == 1 }}
        run: |
          go mod download
      - name: Run GoReleaser
        if: ${{ steps.create_tag.outputs.is_new_tag == 1 }}
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.create_tag.outputs.version }}